CREATE TABLE IF NOT EXISTS comments (
  id VARCHAR PRIMARY KEY,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ,
  author_id VARCHAR NOT NULL,
  article_id VARCHAR NOT NULL
);